name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
- python=3.10
- bzip2
- minimap2<=12.30
- samtools
- bedtools
- bcftools
- whatshap<=2.8
- pip
- pip:
  - numpy
  - pandas
  - pysam
